name: Google Chat Notification

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # New step to set GITHUB_EVENT_TYPE
    - name: Set Event Type
      run: |
        echo "GITHUB_EVENT_TYPE=${{ github.event_name == 'push' && 'PushEvent' || github.event_name == 'pull_request' && 'PullRequestEvent' }}" >> $GITHUB_ENV

    - name: Run Python Script
      run: python .github/scripts/github_details.py
      env:
        GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
        GITHUB_EVENT_TYPE: ${{ env.GITHUB_EVENT_TYPE }}
